name: Security-Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: Scorp10N/devsecops/.github/workflows/security-all.yml@main
    with:
      engine_dockerfile: "./engine"
      web_dockerfile: "./web"
      web_build_args: "VITE_ENGINE_URL=http://localhost:8080"
      go_version: "1.22"
      node_version: "20"
